title: "Hamlet Fernandez Personal Portfolio"
email: hamlet@uchicago.edu
tagline: "A jekyll theme that looks like a shell/terminal"
description: "Hamlet's test portfolio website using jekyll shell theme"
github_username: hamletfernandez
baseurl: ""
url: "https://hamletfernandez.github.io"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - read-me.md
  - preview.md

# set the size of the text to 'large' or 'small', default is small
font-size: small
